### PR TITLE
feat: Add GetDomainsForUser API

### PR DESCRIPTION
**Pull request by Sagilio**
Fixes: #147

Can not update `DynamicExpresso.Core` to v2.5.0: https://github.com/davideicardi/DynamicExpresso/issues/144

### CODE REVIEW

**Comment by hsluoyz** [comment]
@thoraj plz review.

**Comment by thoraj** [comment]
> @thoraj plz review.

I will be happy to review. Is there a nuget feed where I can pick up the build?

**Comment by hsluoyz** [comment]
@Sagilio is there a nightly nuget feed for this PR, which can be used for testing?

**Comment by Sagilio** [comment]
@hsluoyz Secrets are not passed to workflows that are triggered by a pull request from a fork. Pushing myget packages needs the `MYGET_TOKEN`.

**Comment by Sagilio** [comment]
> > @thoraj plz review.
> 
> I will be happy to review. Is there a nuget feed where I can pick up the build?

I have changed the CI. We can merge first, It will release on [MyGet feed](https://www.myget.org/feed/casbin-net/package/nuget/Casbin.NET).

**Comment by Sagilio** [comment]
> @hsluoyz Secrets are not passed to workflows that are triggered by a pull request from a fork. Pushing myget packages needs the `MYGET_TOKEN`.

@hsluoyz So, I try to split the `build and release` to `build` and `release` (use event trigger [here](https://github.com/casbin/Casbin.NET/actions/workflows/release.yml)) and they still use the semantic release. 
I think It will make the release more flexible. e.g.: Sometimes we need more than one PR to release a new version.

**Comment by hsluoyz** [comment]
@Sagilio I didn't see a new release coming after this PR merge. We still should do this:

Let's say the latest version is v1.2.2. When we have new PR:

1. Make nightly release to MyGet for each new PR update, using v1.2.2-1, v1.2.2-2, etc.
2. Make semantic-release to NuGet after PR merge using v1.2.3.

**Comment by Sagilio** [comment]
@hsluoyz We can not release to MyGet from fork repo. 
image

Now, the release policy is:
1. Make nightly release to MyGet after PR merge.
2. Make semantic release to NuGet after manually trigger the release workflow.

I think this is a better way for this repo.  In fact, it more like the build pipeline and release pipeline in Azure DevOps. 
I have triggered a release just now and the v1.8.0 version is released, https://github.com/casbin/Casbin.NET/actions/runs/867798888.

**Comment by hsluoyz** [comment]
@Sagilio how to trigger semantic release?

**Comment by Sagilio** [comment]
@hsluoyz https://github.com/casbin/Casbin.NET/actions/workflows/release.yml
image

**Comment by thoraj** [comment]
I noticed there was a new package v1.8.0 on nuget so I ran some test on that. I got the expected results so LGTM. 

I only tested providing a user parameter like this.

``` csharp
domains = enforcer.GetDomainsForUser("@user1");
```
I did not provide anything for the roleType, as I'm not sure what to expect for these cases.

**Comment by Sagilio** [comment]
@thoraj It will use the default role type.
https://github.com/casbin/Casbin.NET/blob/e5df0b3fe5bcb0d395fe193bd6c7b7c7b7e600a2/NetCasbin/Model/PermConstants.cs#L14

**Pull request merged**
