### PR TITLE
fix: Change lowest TFM form net45 to net452

### LINKED ISSUE #168: Change lowest TFM form net45 to net452

### PR DESCRIPTION
**Pull request by sagilio**
Fix #168, wait for the discussion result.

Fix: https://github.com/casbin/Casbin.NET/issues/168

### CODE REVIEW

**Comment by sagilio** [comment]
close by inactive, wait for the discussion result to request.

**Comment by hsluoyz** [comment]
@sagilio hi, can you fix the conflicts? Thanks!

image

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira plz review

**Review by Leonardo-Ferreira — APPROVED** [review]

**Comment by sagilio** [comment]
@hsluoyz  All conflicts have been resolved.

**Pull request merged**
