### PR TITLE
casbin-rs is now production-ready

### PR DESCRIPTION
**Pull request by GopherJ**

### CODE REVIEW

**Comment by andrexx** [comment]
Hi! Any plans to release version 1.2.5 with build warning fix?

**Comment by hsluoyz** [comment]
@huazhikui @nodece can we release a new version?

**Comment by nodece** [comment]
@hsluoyz yes, v1.2.5 should be released.

**Comment by hsluoyz** [comment]
Let me ping @huazhikui

**Comment by hsluoyz** [comment]
@andrexx v1.2.5 has been released in Nuget: https://www.nuget.org/packages/Casbin.NET/

**Comment by andrexx** [comment]
@hsluoyz  Thanks for your help, I appreciate it.

**Pull request merged**
