### PR TITLE
perf: Support priority deny override model without recursion

### LINKED ISSUE #188: Combine priority and deny-override models
Hi Dev team,

you've recently added explicit priority model support in 1.9.0, many thanks for that.

Is there any chance to support two policy effects at once? For example **Priority** model with **deny override**.
Something like:

```ini
[policy_effect]
e = (priority(p.eft) || deny) || (!some(where (p.eft == deny))) 
```

The value of support such a combined policy effect is that users can have multiple groups assigned with a different eff (allow, deny) and not be dependant on policy position in the file. Please see the example below.

**model.conf**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = priority, sub, obj, act, eft

[role_definition]
g = _, _

[policy_effect]
e = priority(p.eft) || deny

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

------------------------------------------------------------------

**policy.csv**

```csv
p, 10, data1_deny_group, data1, write, deny
p, 10, data1_allow_group, data1, write, allow

g, alice, data1_deny_group
g, alice, data1_allow_group
```

----------------------------------------------------------------
enforcement result of
e.Enforce("alice", "data1", "write") 
will be false, because both groups have the same priority and in this case, Casbin takes the first one, that is deny. 

However, if we switch policy and have a policy file like:

**policy.csv**

```csv
p, 10, data1_allow_group, data1, write, allow
p, 10, data1_deny_group, data1, write, deny

g, alice, data1_deny_group
g, alice, data1_allow_group
```

The result of enforcement - e.Enforce("alice", "data1", "write")  
will be Allow, as first is allow policy.

-----------------------------------------------------------------------------------------------------------------------------
In such cases, when there're multiple groups with the same priority, combine **Priority** and **deny-override** models.
For example, when enforcement happens, casbin can realize that there're multiple matching policies **with the same priority**, and in such cases it can additionally apply a **deny-override** effect?

### PR DESCRIPTION
**Pull request by sagilio**
close #188

### CODE REVIEW

**Comment by sagilio** [comment]
@apiscevs Plz review

**Comment by apiscevs** [comment]
Hi @sagilio ,

thanks for reviewing a refactoring my code.
Approach without a recursion looks good, however there is a one problem.

Code breaks if it did not find a highest level policy, in the result policy result is always false.
Expected result, is that if matching policy were not found on higher tiers, it should dive deeper.

Please use this test to reproduce an issue.

[Fact]
        public void TestPriorityExplicitDenyOverrideWithFakeHighTierPolicyModel()
        {
            var e = new Enforcer(_testModelFixture.GetNewPriorityExplicitDenyOverrideModel());
            e.BuildRoleLinks();
            TestEnforce(e, "alice", "data2", "write", true);
            // adding higher priority policy for alice, however policy's sub, obj and action are fake and never be matched
            //expected enforcement result should be true, as there is a policy with a lower rank 10, that produces allow result
            e.AddPolicy("5", "fake-subject", "fake-object", "very-fake-action", "allow");
            TestEnforce(e, "alice", "data2", "write", true);
        }
        
I've ran this test using initial solution with recursion, it worked successfully.

**Comment by apiscevs** [comment]
looks like it can be easily fixed if check Effect result

if (hasPriority && isPriorityDenyOverrideEfffet **&& nowEffect != Effect.Effect.Indeterminate**)
                    {
                        if (int.TryParse(policyValues[priorityIndex], out int nowPriority))
                        {
                            if (priority.HasValue && nowPriority != priority.Value)
                            {
                                break;
                            }
                            priority = nowPriority;
                        }
                    }

**Comment by sagilio** [comment]
@apiscevs You are right, I have added a new test case, please review again.

**Comment by apiscevs** [comment]
LGTM!
This is way elegant compared to recursion :)

**Pull request merged**
