### PR TITLE
refactor: Change to unique namespace

### PR DESCRIPTION
**Pull request by Sagilio**
Fix: https://github.com/casbin/Casbin.NET/issues/120

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Sagilio why isn't there a semantic PR bot to check the PR title? The PR title should begin with something like "feat: ", "fix:", etc.

I think we claimed that we already supported semantic-release here: https://github.com/casbin/Casbin.NET/issues/37 right?

**Comment by hsluoyz** [comment]
See the bot here: https://github.com/casbin/casbin/pull/702

image

**Comment by Sagilio** [comment]
> @Sagilio why isn't there a semantic PR bot to check the PR title? The PR title should begin with something like "feat: ", "fix:", etc.
> 
> I think we claimed that we already supported semantic-release here: #37 right?

Ok. the bot is ready.

**Comment by hsluoyz** [comment]
@Sagilio plz use:

```
Fix: https://github.com/casbin/Casbin.NET/issues/120
```

instead of

```
close #120
```

in the PR text.

**Comment by hsluoyz** [comment]
@Sagilio plz resolve conflicts.

**Comment by Sagilio** [comment]
> @Sagilio plz use:
> 
> ```
> Fix: https://github.com/casbin/Casbin.NET/issues/120
> ```
> 
> instead of
> 
> ```
> close #120
> ```
> 
> in the PR text.

Ok.

**Comment by hsluoyz** [comment]
@xcaptain

**Review by xcaptain — APPROVED** [review]
LGTM, with some sinple search I found that `readme.md` and `github-actions-release.yaml` contains `NetCasbin`, you can consider change those 2 places.

**Comment by Sagilio** [comment]
> LGTM, with some sinple search I found that `readme.md` and `github-actions-release.yaml` contains `NetCasbin`, you can consider change those 2 places.

Ok, I have changed these places.

**Comment by hsluoyz** [comment]
@Sagilio merged, plz make a breaking change (major version) release.

/cc @xcaptain

**Comment by hsluoyz** [comment]
@Sagilio I don't know why this PR didn't close the issue: https://github.com/casbin/Casbin.NET/issues/120

**Comment by Sagilio** [comment]
> @Sagilio I don't know why this PR didn't close the issue: #120

image
The issue may be not auto-linked.

**Pull request merged**
