### PR TITLE
feat: Add stream adapter.

### PR DESCRIPTION
**Pull request by AsakusaRinne**
Add stream adapter and filtered stream adapter.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@AsakusaRinne plz fix:

image

**Comment by hsluoyz** [comment]
@AsakusaRinne move this code to this repo: https://github.com/casbin-net/stream-adapter

**Comment by hsluoyz** [comment]
@AsakusaRinne fix:

image

**Comment by AsakusaRinne** [comment]
This PR has been moved to #299 to commit to preview branch.

**Pull request closed without merging**
