### PR TITLE
feat: Add globMatch as a global built-in matcher function

### PR DESCRIPTION
**Pull request by dviry**
Fix: https://github.com/casbin/Casbin.NET/issues/231

Implemented as a global built-in function and added related unit tests.

### CODE REVIEW

**Comment by sagilio** [comment]
LGTM, please fix here errors
image

You only need to change the message and add the `-s` param on commit, thank you!
```
git commit -s --amend -m "feat: Add globMatch as a global built-in matcher function"
```

**Comment by hsluoyz** [comment]
@dviry plz fix:

image

cc @Leonardo-Ferreira

**Comment by dviry** [comment]
@hsluoyz Not sure how am I supposed to fix that when all tests completed successfully and the error message states:
```
The format of the analysis property sonar.login= is invalid
```

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira @sagilio can you resolve the Sonar error?

**Review by sagilio — APPROVED** [review]
LGTM

**Comment by sagilio** [comment]
> @dviry plz fix:
> 
> image
> 
> cc @Leonardo-Ferreira

We can skip sonar on PR

**Pull request merged**
