### PR TITLE
ci: Setup SonarCloud Analysis

### PR DESCRIPTION
**Pull request by Leonardo-Ferreira**
This pull request enables the analysis of the project by sonarcloud. 

The reports will be accessible at https://sonarcloud.io/organizations/casbin/projects

A preview of the result can be seen here: https://sonarcloud.io/organizations/leonardo-ferreira/projects

### CODE REVIEW

**Comment by Leonardo-Ferreira** [comment]
@hsluoyz the build is failing with a empty sonar key
image
Idk exactly why though... either you entered the key in the wrong place, or actions triggered by me aren't allowed to read it...
Can you help?

**Review by sagilio — CHANGES_REQUESTED** [review]
Thank you for this PR, I think sonar cloud analysis is not a requirement of build, so it is better to create a new Github workflow to run it.

And the commit message and PR title need a bit fixes for this check: 
image

**Comment by Leonardo-Ferreira** [comment]
@sagilio because the pipeline already runs tests, and all im doing is basically "wrapping" it with `sonar begin/end` I thought it wouldn't be a matter, specially because in the future we can use sonar quality gates to prevent things that hurt the project (bug introduction, test coverage drop, tech debt) to be introduced, and block the PR!
Would you still want to separate the workflows?

**Comment by Leonardo-Ferreira** [comment]
@hsluoyz please create 2 secrets:
SONAR_PROJECT_KEY = casbin_Casbin.NET
SONAR_CASBIN_ORG_NAME = casbin

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira we can try separated workflows first. Done:

image

**Comment by Leonardo-Ferreira** [comment]
image
@huazhikui I broke up the workflows but I think we are back to the previously mentioned issue: either values are empty or my workflow can't/not-allowed-to read them...

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira plz merge the commits into 1 or 2, 23 commits are too many for such a PR..

**Comment by sagilio** [comment]
PR can not read the secret when using GitHub Actions, we can merge it first.

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/Casbin.NET/pull/223

**Pull request closed without merging**
