### PR TITLE
Change the workflow of creating a model

### LINKED ISSUE #52: Change the workflow of creating a model
1. I think we should move the `NewModel` API to Model class. It will follow the [go implement](https://github.com/casbin/casbin/blob/master/model/model.go).
It will be some break changes if we directly delete them, So we can set Obsolete at on them now and remove at the next mainline version.
2. Move the ModelPath field to Model class as a property.  It will we can get the model path when instantiating the Enforcer by model and adapter. It will not any users.
3. Add required section check.

### PR DESCRIPTION
**Pull request by Sagilio**
close #52

### CODE REVIEW

**Comment by hsluoyz** [comment]
Why change to `AddDefine()`?

**Comment by Sagilio** [comment]
> Why change to `AddDefine()`?

Refer to the design of .NET BCL., the method names are usually used the whole word to express clear semantics when the original word is not too long.
But the name should be `AddDefinition` instead of `AddDefine`. It is my mistake and the `AddDef` still is a public method, Change the name may cause the existing project can not compile. So I will change back now，What do you think about it?

**Comment by hsluoyz** [comment]
Yes. Please change back to `AddDef()`

**Comment by Sagilio** [comment]
> Yes. Please change back to `AddDef()`

Ok.

**Pull request merged**
