### PR TITLE
removed x64 platform lock-in

### PR DESCRIPTION
**Pull request by PanzerHabba**
Closing #20

### CODE REVIEW

**Comment by hsluoyz** [comment]
Can you pass the two CIs?

**Comment by PanzerHabba** [comment]
Can it be that the "pull_requests: do_not_increment_build_number" in the appveyor-yaml file is causing this build-error ?

**Comment by hsluoyz** [comment]
@huazhikui can you fix it?

**Comment by TomKearney** [comment]
Hi @huazhikui, is there a plan to push a new version to Nuget.org? Looks like the last release was v1.2.4 made in early December which precedes this change.

**Comment by TomKearney** [comment]
It looks like you've broken the version number convention:

https://specflow.org/documentation/Generate-Tests-from-MsBuild/

It's in this commit:

https://github.com/casbin/Casbin.NET/pull/21/commits/b2a79c372f31d4575aff48246595de9cbc38688f

**Pull request merged**
