### PR TITLE
ci: Changed sonar hook to work for forked PRs - DONT CLOSE YET 

### PR DESCRIPTION
**Pull request by Leonardo-Ferreira**
# DONT CLOSE THIS PR YET

following this article: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira plz fix:

image

**Comment by Leonardo-Ferreira** [comment]
@hsluoyz can you please create the label "sonarcloud analysis pending" and apply it to this PR?

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira done?

**Comment by Leonardo-Ferreira** [comment]
@hsluoyz can you remove the label and add it again pls?

**Comment by Leonardo-Ferreira** [comment]
@hsluoyz can you please remove the label "sonarcloud analysis pending" and add it again?

**Comment by hsluoyz** [comment]
@Leonardo-Ferreira done:

image

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/Casbin.NET/pull/242

**Pull request closed without merging**
